language: ruby
rvm: 1.9.3
script: 
  - bundle exec rspec spec
  - git remote add master git@github.com:codeformexico/api_territory.git
  - git fetch master
  - git checkout master
  - git merge staging
  - git push

